In [4]:
import pandas as pd
import numpy as np
import statistics as stats

In [ ]:
df1 = pd.read_csv(r'\applications(2.0).csv')
df2 = pd.read_csv(r'\industries(2.0).csv')

In [6]:
df1.head(5)

,Applied at,Amount,Age,Gender,Industry,Marital status,External Rating,Education level,Location,applicant_id
0,11.30.2022 10:26:37,12000.0,29,Чоловік,Blockchain,Other,8.0,"Вища (бакалавр, спеціаліст, магістр)",Івано-Франківськ чи область,99e7b0dc6cc05dd334d8f38dc26ce9b3
1,11.30.2022 10:26:39,NaN,36,Чоловік,Public services / Government,Single,3.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,63dfcf8e6904186650d6814279fbe42f
2,11.30.2022 10:26:58,7500.0,34,Чоловік,Adtech / Advertising,Single,4.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,10dbafaeb46c09e96b6987c03bbb3498
3,11.30.2022 10:27:31,1500.0,23,Жінка,Telecom,Single,0.0,"Вища (бакалавр, спеціаліст, магістр)",Львів чи область,5847ac62cc9eac5e323c2517dcc91ad1
4,11.30.2022 10:27:34,8400.0,33,Жінка,Automotive,Single,6.0,"Вища (бакалавр, спеціаліст, магістр)",Житомир чи область,5d21f3795b50de8e8f8f8d5f48b754f3

In [7]:
df2.head(5)

                       Industry  Score
0                    Blockchain      0
1  Public services / Government     20
2          Adtech / Advertising     10
3                       Telecom     15
4                    Automotive     15

In [8]:
df1 = df1.drop_duplicates(subset = 'applicant_id', keep = 'last')
df1['External Rating'] = df1['External Rating'].fillna(0)
df1['Education level'] = df1['Education level'].fillna('Середня')

df1.head(5)

,Applied at,Amount,Age,Gender,Industry,Marital status,External Rating,Education level,Location,applicant_id
1,11.30.2022 10:26:39,NaN,36,Чоловік,Public services / Government,Single,3.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,63dfcf8e6904186650d6814279fbe42f
2,11.30.2022 10:26:58,7500.0,34,Чоловік,Adtech / Advertising,Single,4.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,10dbafaeb46c09e96b6987c03bbb3498
3,11.30.2022 10:27:31,1500.0,23,Жінка,Telecom,Single,0.0,"Вища (бакалавр, спеціаліст, магістр)",Львів чи область,5847ac62cc9eac5e323c2517dcc91ad1
4,11.30.2022 10:27:34,8400.0,33,Жінка,Automotive,Single,6.0,"Вища (бакалавр, спеціаліст, магістр)",Житомир чи область,5d21f3795b50de8e8f8f8d5f48b754f3
5,11.30.2022 10:27:38,16500.0,31,Чоловік,E-commerce,Single,8.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,f720bf9c5c4c3e10a8568c1699847696

In [9]:
df_merg = df1.merge(df2, on = 'Industry', how = 'left')
df_merg

,Applied at,Amount,Age,Gender,Industry,Marital status,External Rating,Education level,Location,applicant_id,Score
0,11.30.2022 10:26:39,NaN,36,Чоловік,Public services / Government,Single,3.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,63dfcf8e6904186650d6814279fbe42f,20
1,11.30.2022 10:26:58,7500.0,34,Чоловік,Adtech / Advertising,Single,4.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,10dbafaeb46c09e96b6987c03bbb3498,10
2,11.30.2022 10:27:31,1500.0,23,Жінка,Telecom,Single,0.0,"Вища (бакалавр, спеціаліст, магістр)",Львів чи область,5847ac62cc9eac5e323c2517dcc91ad1,15
3,11.30.2022 10:27:34,8400.0,33,Жінка,Automotive,Single,6.0,"Вища (бакалавр, спеціаліст, магістр)",Житомир чи область,5d21f3795b50de8e8f8f8d5f48b754f3,15
4,11.30.2022 10:27:38,16500.0,31,Чоловік,E-commerce,Single,8.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,f720bf9c5c4c3e10a8568c1699847696,15
...,...,...,...,...,...,...,...,...,...,...,...
13273,01.09.2023 11:01,12000.0,25,Чоловік,Medtech / Healthcare,Single,6.0,"Вища (бакалавр, спеціаліст, магістр)",Харків чи область,01908b949a6a1eb44d1ee013ec377f9d,15
13274,01.09.2023 11:14,10500.0,28,Чоловік,Blockchain,Married,5.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,6599ba629cfcfe8ac42c7d31c13f62de,0
13275,01.09.2023 11:19,5790.0,25,Чоловік,Blockchain,Married,3.0,"Вища (бакалавр, спеціаліст, магістр)",Дніпро чи область,e57f181bec5b11870a541c43d9b960f7,0
13276,01.09.2023 11:28,13500.0,31,Чоловік,Mobile,Single,8.0,Середня,Одеса чи область,a340c62a1226509949ef60df10a7d726,15
13277,01.09.2023 11:38,12600.0,32,Чоловік,High Load Systems,Married,11.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,a36a922c50b554cad6cd0eb98a5eaad8,15

In [ ]:
df_merg['Rating'] = 0
df_merg['Rating'] += df_merg['Score']
df_merg.loc[df_merg['Age'].between(35, 55), 'Rating'] += 20
df_merg.loc[df_merg['Marital status'] == 'Married', 'Rating'] += 20
df_merg.loc[df_merg['Location'] == 'Київ чи область', 'Rating'] += 10
df_merg.loc[df_merg['External Rating'] >= 7.0, 'Rating'] += 20
df_merg.loc[df_merg['External Rating'] <= 2.0, 'Rating'] -= 20

df_merg['Applied at'] = pd.to_datetime(df_merg['Applied at'], dayfirst=True, errors='coerce')
df_merg.loc[df_merg['Applied at'].dt.weekday <= 4, 'Rating'] += 20
df_merg

C:\Users\Anna\AppData\Local\Temp\ipykernel_53412\1237971263.py:9: UserWarning: Parsing dates in %m.%d.%Y %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_merg['Applied at'] = pd.to_datetime(df_merg['Applied at'], dayfirst=True, errors='coerce') # coerse змінює помилки на nat (not a time)

,Applied at,Amount,Age,Gender,Industry,Marital status,External Rating,Education level,Location,applicant_id,Score,Rating
0,2022-11-30 10:26:39,NaN,36,Чоловік,Public services / Government,Single,3.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,63dfcf8e6904186650d6814279fbe42f,20,60
1,2022-11-30 10:26:58,7500.0,34,Чоловік,Adtech / Advertising,Single,4.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,10dbafaeb46c09e96b6987c03bbb3498,10,40
2,2022-11-30 10:27:31,1500.0,23,Жінка,Telecom,Single,0.0,"Вища (бакалавр, спеціаліст, магістр)",Львів чи область,5847ac62cc9eac5e323c2517dcc91ad1,15,15
3,2022-11-30 10:27:34,8400.0,33,Жінка,Automotive,Single,6.0,"Вища (бакалавр, спеціаліст, магістр)",Житомир чи область,5d21f3795b50de8e8f8f8d5f48b754f3,15,35
4,2022-11-30 10:27:38,16500.0,31,Чоловік,E-commerce,Single,8.0,"Вища (бакалавр, спеціаліст, магістр)",Київ чи область,f720bf9c5c4c3e10a8568c1699847696,15,65
...,...,...,...,...,...,...,...,...,...,...,...,...
13273,NaT,12000.0,25,Чоловік,Medtech / Healthcare,Single,6.0,"Вища (бакалавр, спеціаліст, магістр)",Харків чи область,01908b949a6a1eb44d1ee013ec377f9d,15,15
13274,NaT,10500.0,28,Чоловік,Blockchain,Married,5.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,6599ba629cfcfe8ac42c7d31c13f62de,0,20
13275,NaT,5790.0,25,Чоловік,Blockchain,Married,3.0,"Вища (бакалавр, спеціаліст, магістр)",Дніпро чи область,e57f181bec5b11870a541c43d9b960f7,0,20
13276,NaT,13500.0,31,Чоловік,Mobile,Single,8.0,Середня,Одеса чи область,a340c62a1226509949ef60df10a7d726,15,35
13277,NaT,12600.0,32,Чоловік,High Load Systems,Married,11.0,"Вища (бакалавр, спеціаліст, магістр)",NaN,a36a922c50b554cad6cd0eb98a5eaad8,15,55

In [11]:
df_merg.shape

(13278, 12)

In [12]:
df_filt = df_merg[df_merg['Rating'].between(0, 100)]
df_filt.shape

(12778, 12)

In [18]:
df_filt.groupby(df_filt['Applied at'].dt.to_period('W'))['Rating'].mean().round(1)

Applied at
2022-11-28/2022-12-04    51.7
2022-12-12/2022-12-18    46.3
2022-12-19/2022-12-25    45.2
2022-12-26/2023-01-01    49.4
Freq: W-SUN, Name: Rating, dtype: float64